### PR TITLE
Add milestones!

### PR DESCRIPTION
**Pull request by CarterAppleton**
Add markers in the progress bar itself! For https://github.com/ConstitutionDAO/www/issues/27
- Markers are defined in the html - if you want more or the change the name (maybe emojis!), just add more divs
- Multiple divs gives the option to color/gradient each part differently. Choosing a color went way over my head for this pr, but you could have like `blue - Qualify`, `green - Compete`, `red - Stretch`
- Animation now masks the inner divs so it all animates together

Screen Shot 2021-11-17 at 19 31 04

### CODE REVIEW

**Comment by CarterAppleton** [comment]
Video preview:
https://user-images.githubusercontent.com/338126/142347073-7aca4a93-25c4-4b11-a18c-96fdc615a10c.mov

**Comment by CarterAppleton** [comment]
Video preview:


https://user-images.githubusercontent.com/338126/142347251-e26d05b9-0b70-4a12-bd1d-c9076f71c55b.mov

**Comment by rhythms06** [comment]
"Qualify" and "Compete" are ambiguous to anyone not familiar with the project - could we add milestone details on hover perhaps?

**Comment by CarterAppleton** [comment]
Changed description to emojis and added some mouseovers (people on mobile can click on a section for the details to appear!)

Screen Shot 2021-11-17 at 22 14 30

**Pull request closed without merging**
